environment:
  matrix:
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python36-x64"

install:
  - "%PYTHON%\\python.exe -m pip install --upgrade pip"
  - "%PYTHON%\\python.exe -m pip install --upgrade wheel setuptools"
  - "%PYTHON%\\python.exe -m pip install --upgrade tox"

build: off

test_script:
  - "%PYTHON%\\python.exe -m tox"
