environment:
  matrix:
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python36-x64"

install:
  - "%PYTHON%\\python.exe -m pip install --upgrade pip"
  - "%PYTHON%\\python.exe -m pip install --upgrade wheel setuptools>=37"
  - "%PYTHON%\\python.exe -m pip install \".[ci]\" -c requirements.txt"

build: off

test_script:
  - "%PYTHON%\\python.exe setup.py test"
  - "%PYTHON%\\python.exe setup.py check -srm"
