matrix:
  include:
    - os: osx
      language: generic
      before_install:
        - brew update
        - brew install python3
        - virtualenv env -p python3
        - source env/bin/activate
    - os: linux
      language: python
      python: 3.6
    - os: linux
      language: python
      python: 3.6-dev
    - os: linux
      language: python
      python: 3.7-dev
    - os: linux
      language: python
      python: nightly

install:
  - python -m pip install --upgrade pip
  - python -m pip install ".[ci]" -c requirements.txt

script:
  - python setup.py test
  - python setup.py check -srm

after_success:
  - flake8 async_app
  - codecov

deploy:
  provider: pypi
  user: Ilya.Kulakov
  password:
    secure: "B8CzSceE2kMZeHnYJMrk8uowtFhYT62lbQbL1DK+GLdOZr6bMgt79XI+gXKW1OmVKL5mg3b/2PnaEmuyTxpqJYvK3M+BVw608hcSkCfvsSY/EY6GVF0iFYywaCLobrC5h+1z+mUuI4r9+0Gq50wjb9J27SyVVHS9yDVuW+D7x/c6QEftKcjILs8UBmal/Oa3HNG9cZ8YjDvXlVEP3krhCaTGiv/MQW/yt1QCGsUy3zQfkOsParFFfwt53m/KfiFZOHGBly2T3fY3miVCm6x227lodzhZ08doAJ8rCVU6zHNPChvNC9ECsxcrozoIm9G9c6trkeuIAOkE2hvY2pEq7IA6pwRANJe0GM4of2iOXXibsrM+ZkzmWIBX41Ns6BxDRGxiDzWm29xeYZX7hvkkQo+0iQx7AMJNXKHewuhMXetKga8Tpcs2/xurLDCbgtN/YvRF7UjrHARxnluLeTzTdA0vLwgJ3nGUAHaX9fguHVT5FRBExn8AN9HwDfvTAflzR4RgIqTBM2QtUyJMHc3jSQXU4L2VZzd+r40Gr1ld+7WTGO6GifgueIb6G7NfWtn2j/FtKmHfAB8Hdza3Fb0HhbaZhAPo01s6o+joxzPT32aVMt42FWAV8LQUUWhz3j8bV9oneL8oNVWcn5gBYNdngTmlDMe5rYIEeCEoZhNnhtc="
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    branch: master
    python: 3.6